# Analise Dataset

Esta arquivo foi idealizada como conclusão para a disciplina de analise de dados.

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [20]:
copa_2014 = pd.read_csv('FIFA - 2014.csv')

In [21]:
copa_2014

,Position,Team,Games Played,Win,Draw,Loss,Goals For,Goals Against,Goal Difference,Points
0,1,Germany,7,6,1,0,18,4,14,19
1,2,Argentina,7,5,1,1,8,4,4,16
2,3,Netherlands,7,5,2,0,15,4,11,17
3,4,Brazil,7,3,2,2,11,14,−3,11
4,5,Colombia,5,4,0,1,12,4,8,12
5,6,Belgium,5,4,0,1,6,3,3,12
6,7,France,5,3,1,1,10,3,7,10
7,8,Costa Rica,5,2,3,0,5,2,3,9
8,9,Chile,4,2,1,1,6,4,2,7
9,10,Mexico,4,2,1,1,5,3,2,7
10,11,Switzerland,4,2,0,2,7,7,0,6
11,12,Uruguay,4,2,0,2,4,6,−2,6
12,13,Greece,4,1,2,1,3,5,−2,5
13,14,Algeria,4,1,1,2,7,7,0,4
14,15,United States,4,1,1,2,5,6,−1,4
15,16,Nigeria,4,1,1,2,3,5,−2,4
16,17,Ecuador,3,1,1,1,3,3,0,4
17,18,Portugal,3,1,1,1,4,7,−3,4
18,19,Croatia,3,1,0,2,6,6,0,3
19,20,Bosnia and Herzegovina,3,1,0,2,4,4,0,3
20,21,Ivory Coast,3,1,0,2,4,5,−1,3
21,22,Italy,3,1,0,2,2,3,−1,3
22,23,Spain,3,1,0,2,4,7,−3,3
23,24,Russia,3,0,2,1,2,3,−1,2
24,25,Ghana,3,0,1,2,4,6,−2,1
25,26,England,3,0,1,2,2,4,−2,1
26,27,South Korea,3,0,1,2,3,6,−3,1
27,28,Iran,3,0,1,2,1,4,−3,1
28,29,Japan,3,0,1,2,2,6,−4,1
29,30,Australia,3,0,0,3,3,9,−6,0
30,31,Honduras,3,0,0,3,1,8,−7,0
31,32,Cameroon,3,0,0,3,1,9,−8,0

In [22]:
jogos_jogados = np.array(copa_2014.loc[0:,'Games Played'])
qtd_jogos = np.sum(jogos_jogados)
print('Teve o total de',qtd_jogos,'jogos.')

Teve o total de  128 jogos

In [25]:
gol_contra = np.array(copa_2014.loc[0:,'Goals Against'])
qtd_gol_contra = np.sum(gol_contra)
print('Teve o total de',qtd_gol_contra,'gols contra.')

Teve o total de 171 gols contra.